### PR TITLE
Update Wasmtime to v23.0.1.

### PR DESCRIPTION
**Pull request by martijneken**

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Could you re-kick the CI? I think the default branch name change broke the results.

**Comment by martijneken** [comment]
> Could you re-kick the CI? I think the default branch name change broke the results.

Aha yes, I caused a problem with the name changes: https://github.com/search?q=org%3Aproxy-wasm+master+path%3A.github&type=code

Drafting and sending fixes as separate PRs.

**Comment by mpwarres** [comment]
LGTM, but let's confirm that CI passes with #21 merged.

**Comment by PiotrSikora** [comment]
Could you update it to latest?

**Comment by martijneken** [comment]
Updated, PTAL

**Review by PiotrSikora — APPROVED** [review]
Thanks!

**Pull request merged**
